// MLDialog.cpp : インプリメンテーション ファイル
//

#include "stdafx.h"
#include "syaku8.h"
#include "MLDialog.h"
#include "tuner.h"
#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CMLDialog ダイアログ


CMLDialog::CMLDialog(CWnd* pParent /*=NULL*/)
	: CDialog(CMLDialog::IDD, pParent)
{
	//{{AFX_DATA_INIT(CMLDialog)
	//}}AFX_DATA_INIT
	Create(CMLDialog::IDD,pParent);
}


void CMLDialog::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	//{{AFX_DATA_MAP(CMLDialog)
	DDX_Control(pDX, IDC_LIST, m_help);
	//}}AFX_DATA_MAP
}


BEGIN_MESSAGE_MAP(CMLDialog, CDialog)
	//{{AFX_MSG_MAP(CMLDialog)
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CMLDialog メッセージ ハンドラ
void CMLDialog::OnOK() 
{
	DestroyWindow();	
//	CDialog::OnOK();
}

void CMLDialog::PostNcDestroy() 
{
	delete this;	
//	CDialog::PostNcDestroy();
}


BOOL CMLDialog::OnInitDialog() 
{

	CDialog::OnInitDialog();
	char *htxt[1000];
	int i,n=0;
#ifndef English
	htxt[n++]="============================================================";
	htxt[n++]="                    尺八運指チューナー";
	htxt[n++]="============================================================";
	htxt[n++]="　";
	htxt[n++]="（１）オートチューナーとしての機能";
	htxt[n++]="左下枠に入力音の周波数が数値表示されます。入力音に一番近い音";
	htxt[n++]="律とそれとのずれが表示されます。";
	htxt[n++]="左下の中ほどの枠にＡのピッチが表示されます。その両脇のボタン";
	htxt[n++]="で375Hzから470Hzの範囲でピッチを設定できます。設定変更を次回";
	htxt[n++]="起動時にも有効にするにはメニューから「Ａのピッチを記憶」をチ";
	htxt[n++]="ェックして下さい。";
	htxt[n++]="左上枠には入力音の現波形、FFT波形、五線譜とセント表示のいずれ";
	htxt[n++]="かが表示されますが、メニューから選択します。";
	htxt[n++]=" ";
	htxt[n++]="（２）メモリー機能";
	htxt[n++]="リターンキーでリアルタイム表示を停止させると、それまでに記憶";
	htxt[n++]="されたおよそ1100個の入力音のデータ（波形、音量、周波数など）";
	htxt[n++]="を左右カーソルキーで表示させることができます。リターンキーで";
	htxt[n++]="再びリアルタイム表示に戻ります。シフト＋リターンキーでリアル";
	htxt[n++]="タイム表示に戻すと、それまでの入力音データをクリアすることが";
	htxt[n++]="出来ます。";
	htxt[n++]="リアルタイム表示停止時には、入力音波形をＳＡＶＥボタンでファ";
	htxt[n++]="イルに書き込むことができます。";
	htxt[n++]="表示メニューが「五線譜とセント表示」の時は、指定した範囲の入";
	htxt[n++]="力音の音律とセントが記憶できます。ドラッグ操作で範囲を指定で";
	htxt[n++]="きます。";
	htxt[n++]=" ";
	htxt[n++]="（３）運指表示機能";
	htxt[n++]="琴古流、都山流尺八のほか、篠笛、能管、フルート、オカリナ、ク";
	htxt[n++]="ラリネット、サキソフォーン、ホルン、トロンボーン、トランペッ";
	htxt[n++]="ト、リコーダーなどの運指図が見れます。";
	htxt[n++]="メニューもしくは楽器のボタンで楽器を選ぶと、入力音に一番近い";
	htxt[n++]="音律の運指が右下枠に表示されます。";
	htxt[n++]="右中ほどのスライドバーで調子笛の音を出して、その下の４個の";
	htxt[n++]="ボタンで音高を変化させると任意の運指を確認できます。";
	htxt[n++]=" ";
	htxt[n++]="（４）音量測定機能";
	htxt[n++]="右上枠に棒グラフと数値(dB)で音量が表示されます。棒グラフ枠内";
	htxt[n++]="での最大音量はその位置が枠下部に赤いドットで示されます。リタ";
	htxt[n++]="ーンキーで一時停止すると、クリックや左右カーソルキーでその音";
	htxt[n++]="量が確認出来ます。";
	htxt[n++]="dBの基準値音量は音量表示枠左の上下ボタンで変更できます。マイ";
	htxt[n++]="ク、サウンドカード、ボリュームコントロールの設定変更などでdB";
	htxt[n++]="表示値は変化します。";
	htxt[n++]=" ";
	htxt[n++]="（５）調子笛機能";
	htxt[n++]="調子笛として使えます。調子音の種類は、サイン波、のこぎり波、";
	htxt[n++]="矩形波、三角波の４種です。右中央部にその波形が図示されています";
	htxt[n++]="が、そこをクリックすると種類を変更できます。スライドバーで音";
	htxt[n++]="量を設定します。";
	htxt[n++]=" ";
	htxt[n++]="（６）入力音の表示";
	htxt[n++]="現波形とＦＦＴ波形が各々３種類の範囲で表示できます。ＦＦＴ波";
	htxt[n++]="形はそのもの(Lineal)と対数(Logarithmic)表示が選択できます。";
	htxt[n++]="対数表示の場合PageUpとPageDownキーで表示位置を調節できます。";
	htxt[n++]="五線譜とセント表示では、波形ではなく音律とセントが表示されます。";
	htxt[n++]=" ";
	htxt[n++]="（７）マウス操作のヘルプとマウス以外で使えるキー";
	htxt[n++]="ボタンや表示枠の中にマウスカーソルをもっていくと、左最下行に";
	htxt[n++]="機能や操作法の説明が表示されます。";
	htxt[n++]="操作のほとんどはマウスで行いますが、上下左右カーソルキー、リ";
	htxt[n++]="ターンキー、シフトキー＋リターンキー、Ａ、Ｍ キーも使えます。";
	htxt[n++]=" ";
	htxt[n++]="（８）フィルターの設定";
	htxt[n++]="マイク内臓タイプのパソコンで作動させたとき、電源ファンなどの";
	htxt[n++]="雑音が混入しうまく周波数測定できないことがあります。";
	htxt[n++]="その時は、「表示」メニューを「ＦＦＴ波形」として、雑音成分の";
	htxt[n++]="周波数を読み取って、パラメータファイル：ｓｙａｋｕ８．ｉｎｉ";
	htxt[n++]="に、その周波数を含む帯域カットフィルタを設定してください。";
	htxt[n++]="たとえば";
	htxt[n++]=" ";
	htxt[n++]="Zone Cut Filter 1 Lower Limit(0-5000):180";
	htxt[n++]="Zone Cut Filter 1 Upper Limit(0-5000):200";
	htxt[n++]=" ";
	htxt[n++]="とすると、１８０Hzから２００Hzまでの周波数成分を計算から除外";
	htxt[n++]="します。";
	htxt[n++]="============================================================";
	htxt[n++]="http://www.shaku6.com";
	htxt[n++]="============================================================";
#else
	htxt[n++]="-------------------------------------------------------------------";
htxt[n++]="               Auto Tuner with fingering charts";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 1 - About the Auto Tuner";
htxt[n++]=" ";
htxt[n++]="1.1  Introduction";
htxt[n++]=" ";
htxt[n++]="The Auto Tuner offers many useful features for musical instrument ";
htxt[n++]="makers and players not found in other tuners.  It can measure the";
htxt[n++]="pitch and the  loudness of notes, with a choice of manual or auto-";
htxt[n++]="matic note selection. It can show a spectrum analysis of the note,";
htxt[n++]="allowing the player to compare the  harmonic structure  of  their ";
htxt[n++]="notes with those of another player or instrument.  It can  keep a ";
htxt[n++]="record of up to 1100 samples, permitting the player to review the ";
htxt[n++]="pitch, loudness and spectrum of each sample after playing. It can";
htxt[n++]="be used to generate musical tones in several useful tone colours.  ";
htxt[n++]="Finally, it shows the standard fingering pattern for each note on ";
htxt[n++]="a range of Japanese and Western musical instruments.";
htxt[n++]=" ";
htxt[n++]="1.2  System requirements:";
htxt[n++]=" ";
htxt[n++]="A sound card and microphone are needed  to use  this  program. If ";
htxt[n++]="you are only interested  in  tuning (measuring pitch),  then  the ";
htxt[n++]="microphone can be very basic.  Even  a  set of  headphones  or an ";
htxt[n++]="unpowered loudspeaker plugged into the microphone  input  of  the ";
htxt[n++]="soundcard will suffice.       Another option is to use a portable ";
htxt[n++]="cassette recorder in record-pause mode,  plugged  into  the sound ";
htxt[n++]="card's line input. If, however, you are also interested in measur-";
htxt[n++]="ing level and tonal quality accurately,  a better quality ";
htxt[n++]="microphone is needed.";
htxt[n++]=" ";
htxt[n++]="The Auto Tuner can also be used to analyse sounds recorded on tape ";
htxt[n++]="or CD if these devices are connected to the sound card.";
htxt[n++]=" ";
htxt[n++]="To generate audible tones  from the tuner, the sound card must be ";
htxt[n++]="connected to one or more speakers.";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 2 - Configuring the Auto Tuner";
htxt[n++]=" ";
htxt[n++]="2.1  Enabling the input device:";
htxt[n++]=" ";
htxt[n++]="After connecting the microphone or line input, run the Windows ";
htxt[n++]="Recording Control program from the Options menu (Sound Input, I).";
htxt[n++]="Check the desired input device and move the associated fader to ";
htxt[n++]="about half way up.";
htxt[n++]=" ";
htxt[n++]="Minimise the \"Recording Control\" and return to the Auto Tuner.  It ";
htxt[n++]="should now be attempting to analyse  the background  noise in the ";
htxt[n++]="room.  If not, check the operation of the sound card (see next ";
htxt[n++]="section).";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="2.2  Check Sound Card";
htxt[n++]=" ";
htxt[n++]="If you select Check Sound Card (E) from the Options menu, you ";
htxt[n++]="should hear a test tone from the computer loudspeakers, and see ";
htxt[n++]="the tuner attempting to read the pitch of the note picked up by ";
htxt[n++]="the microphone.  ";
htxt[n++]=" ";
htxt[n++]="If you can't hear the tone,  check your speakers and  soundcard ";
htxt[n++]="replay section are connected and set appropriately.  ";
htxt[n++]=" ";
htxt[n++]="If you can hear the tone, but a message appears saying that the ";
htxt[n++]="sound for calibration seems not to be detected, try turning the ";
htxt[n++]="speaker volume up.    If still not succesful, check  the  input ";
htxt[n++]="settings as outlined in Section 2.1.  ";
htxt[n++]=" ";
htxt[n++]="If the tuner can read the tone but does not read centre, press the ";
htxt[n++]="OK button in the dialog box that will appear.   Otherwise  press ";
htxt[n++]="cancel.";
htxt[n++]=" ";
htxt[n++]="When finished with the Sound Card Check, turn down the slide fader ";
htxt[n++]="on the right centre of screen.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="2.3 Adjusting the input level:";
htxt[n++]=" ";
htxt[n++]="To get the best results, it is desirable to set the  input (micro-";
htxt[n++]="phone or line) as high as possible without overload. Position the ";
htxt[n++]="Windows \"Volume Control\" over the  Tuner so as not to obscure the ";
htxt[n++]="Tuner's Sample window (just under the Sound V. window). Play the ";
htxt[n++]="loudest sound you are likely to measure into the input device.  ";
htxt[n++]="Advance the input device fader until the tips of the samples turn ";
htxt[n++]="Yellow. Bring the fader down if the indicator shows Red.";
htxt[n++]=" ";
htxt[n++]="For reference, yellow tips appear when the input level is from -6dB";
htxt[n++]="to -3dB of maximum level.  Red tips appear between -3dB and Maximum";
htxt[n++]="level.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="2.4  Navigating the Tuner panel:";
htxt[n++]=" ";
htxt[n++]="Most Tuner operations can be controlled by using the Mouse.  Move";
htxt[n++]="the mouse cursor over a button and a Help message will  appear in  ";
htxt[n++]="the bottom left corner. ";
htxt[n++]=" ";
htxt[n++]="It is also possible to use many of the  keyboard keys - their use ";
htxt[n++]="will be discussed under the relevant sections.";
htxt[n++]=" ";
htxt[n++]="Watch also for useful messages in the bottom left corner of the ";
htxt[n++]="tuner when the mouse is held over any button";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="2.5  Choosing a sampling rate";
htxt[n++]=" ";
htxt[n++]="The Auto Tuner can sample the incoming signals at three different ";
htxt[n++]="rates, selected from the Options pull down.  \"Slow\" is convenient ";
htxt[n++]="for most purposes.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="2.6  Choosing how notes are displayed";
htxt[n++]=" ";
htxt[n++]="In the options menu,you can select whether notes are to be called ";
htxt[n++]="by their letters  (for example C, D, E) or  by their tonic sol-fa ";
htxt[n++]="names (Do, Re, Mi).";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 3 - Pitch measurements";
htxt[n++]=" ";
htxt[n++]="3.1  Selecting Pitch Mode:";
htxt[n++]=" ";
htxt[n++]="The Tuner has two modes for measuring the pitch  of sounds played ";
htxt[n++]="into it. Select between Automatic and Manual by pressing the ";
htxt[n++]="Manu/Auto button with the mouse, or pressing the  M and A buttons ";
htxt[n++]="on the keyboard.  Yellow indicators beside the button show  which ";
htxt[n++]="mode is on.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="3.2  Automatic Pitch Mode:";
htxt[n++]=" ";
htxt[n++]="In automatic mode, the Tuner will automatically detect the appro-";
htxt[n++]="priate octave and the nearest semitone, and will indicate how far ";
htxt[n++]="(in cents)the note is from that semitone.(A cent is one hundredth ";
htxt[n++]="of a semitone.)  ";
htxt[n++]=" ";
htxt[n++]="The maximum deviation from the semitone will be +/- 50 cents.  If ";
htxt[n++]="the note drifts further from the nominal pitch , the  tuner  will ";
htxt[n++]="switch to the next semitone.";
htxt[n++]=" ";
htxt[n++]="The number that appears beside the semitone name indicates which ";
htxt[n++]="octave the note is in.  The internationally agreed system is used, ";
htxt[n++]="where C4 is \"middle\" C, the C note in the middle of the piano ";
htxt[n++]="keyboard.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="3.3  Manual Pitch Mode";
htxt[n++]=" ";
htxt[n++]="In manual pitch mode,  it  is necessary to advise the Tuner which   ";
htxt[n++]="octave and which semitone is intended. This can be done using the ";
htxt[n++]="mouse to press the buttons to the right of the Manu/Auto  button, ";
htxt[n++]="or using the Up and Down arrows on the keyboard.";
htxt[n++]=" ";
htxt[n++]="In manual mode, the pitch meter shows up to +/- 100 cents.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="3.4  The \"Near Enough\" indicator";
htxt[n++]=" ";
htxt[n++]="In the Options pull down,  you will find four \"Disp\" choices - 0, ";
htxt[n++]="10, 20 and 30 cents.  If, for example, 20 cents is chosen,a blue ";
htxt[n++]="highlight appears on the pitch meter dial when the incoming note ";
htxt[n++]="is  within +/- 20 cents of the nearest or selected semitone.  If ";
htxt[n++]="0 is selected, the option is disabled.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="3.5  Measuring and Indicating Frequency (Hz)";
htxt[n++]=" ";
htxt[n++]="As musicians, we are generally more interested in measuring pitch ";
htxt[n++]="(in octaves, semitones and cents) than frequency (in Hertz or Hz).  ";
htxt[n++]="The frequency of  the  incoming  note is however displayed in the ";
htxt[n++]="window at the bottom of the screen.  The frequency of the nearest ";
htxt[n++]="semitone is indicated at the top  of the meter, with those of the ";
htxt[n++]="semitones above and below at the left and right ends of the meter ";
htxt[n++]="dial.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="3.6  Choosing a different Reference Pitch";
htxt[n++]=" ";
htxt[n++]="By international agreement, the note A is now defined as having a ";
htxt[n++]="frequency of 440 vibrations per second (A 440Hz). But researchers ";
htxt[n++]="of older instruments may be concerned with  instruments  designed ";
htxt[n++]="to play at very different pitches. For this reason,the Auto-tuner ";
htxt[n++]="has been given a very wide range of reference pitches.  ";
htxt[n++]=" ";
htxt[n++]="The reference pitch is shown in a window below the note window in ";
htxt[n++]="the centre of the pitch meter.  The default is 440 Hz.  To change ";
htxt[n++]="the reference pitch, use the mouse to press the buttons on either ";
htxt[n++]="side of the reference pitch window. For normal use, make sure the ";
htxt[n++]="pitch indicated is 440.";
htxt[n++]=" ";
htxt[n++]="You can have the Auto-tuner default to A440 at launch by choosing  ";
htxt[n++]="\"A=440 at first\"  on the Options menu.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="3.8 Eliminating spurious measurements";
htxt[n++]=" ";
htxt[n++]="If  the microphone is picking up room noises such as the computer ";
htxt[n++]="fan, these may confuse the pitch measurement system.  Two ";
htxt[n++]="Zone Cut Filters have been provided to deal with them. By reading ";
htxt[n++]="the frequency of the offending signal from  the  FFT  display you ";
htxt[n++]="will then be able to set the Zone Cut Filter to cut out the noise.";
htxt[n++]=" ";
htxt[n++]="When the  program  is  first  launched,   a parameter file called ";
htxt[n++]="s8tuner.ini will be created. Close the tuner program, open  the  ";
htxt[n++]="s8tuner.ini file in a text editor and you will find the two Zone ";
htxt[n++]="Cut Filter definitions.   They  may be edited to exclude the ";
htxt[n++]="annoying tone from affecting the tuner.  For example:";
htxt[n++]=" ";
htxt[n++]="Zone Cut Filter 1 Lower Limit: (0-5000): 180";
htxt[n++]="Zone Cut Filter 1 Upper Limit: (0-5000): 200";
htxt[n++]=" ";
htxt[n++]="In the above example, the program will sut out  all  frequencies ";
htxt[n++]="above 200Hz and below 180Hz. The parts of the spectrum covered by ";
htxt[n++]="the filters is shown on the FFT graph as horizontal grey bands ";
htxt[n++]="just above the frequency calibrations.";
htxt[n++]=" ";
htxt[n++]="Keep in mind that a zone cut filter set around the frequency of a ";
htxt[n++]="note will prevent the tuner from reacting to that note.";
htxt[n++]=" ";
htxt[n++]="3.9 Just Intonation";
htxt[n++]=" ";
htxt[n++]="Modern instruments are generally tuned to \"Equal Temperament\", a ";
htxt[n++]="system where each semitone has equal value, permitting easy ";
htxt[n++]="modulation into other keys.  In earlier times and other cultures, ";
htxt[n++]="\"Just Intonation\" is preferred.  Instead of tuning to mathematic-";
htxt[n++]="ally calculated semitones, instruments are tuned  so  that  the ";
htxt[n++]="intervals between notes are most musically harmonious. Selecting ";
htxt[n++]="\"Just Intonation\" on the Options menu will  switch on  small red ";
htxt[n++]="marker dots on the tuner scale, with the intervals they represent ";
htxt[n++]="to the key note chosen by the Key buttons at the bottom right of ";
htxt[n++]="screen (See Section 8).  ";
htxt[n++]=" ";
htxt[n++]="A web search on \"just intonation intervals\" will reveal";
htxt[n++]="which numerical ratios are appropriate to which musical intervals";
htxt[n++]="in various cultures.";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 4 - Generating audible tones";
htxt[n++]=" ";
htxt[n++]="4.1 Enabling audible tones";
htxt[n++]=" ";
htxt[n++]="Above  the  Manu/Auto  button will be found  a button and a fader.  ";
htxt[n++]="These control the playback of sounds generated by the Tuner.These ";
htxt[n++]="sounds may be used to tune an instrument by ear.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="4.2  Choosing the audible sound quality";
htxt[n++]=" ";
htxt[n++]="The button selects the waveform to be heard. The sine wave is the ";
htxt[n++]="ultimately pure tone.  The others - the triangle wave,  saw-tooth ";
htxt[n++]="wave, and square wave - are rich in various harmonics. In general, ";
htxt[n++]="harmonically rich waveforms are easier to tune to by ear.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="4.3  Loudness of audible sound";
htxt[n++]=" ";
htxt[n++]="The fader controls the volume of sound produced.  Keep it set to ";
htxt[n++]="the minimum during visual tuning.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="4.4  Selecting the pitch to be heard.";
htxt[n++]=" ";
htxt[n++]="Normally,  the sound  generator will be used in the Manual  mode, ";
htxt[n++]="selecting the desired note with the four buttons below the fader.  ";
htxt[n++]="Some interesting interactive  effects are  possible in  Automatic ";
htxt[n++]="mode however.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 5 - Measuring Sound Level";
htxt[n++]=" ";
htxt[n++]="5.1  Sound Volume";
htxt[n++]=" ";
htxt[n++]="The Sound Volume window provides a constantly updated measure of ";
htxt[n++]="the current sound level, expressed in dB.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="5.2  Calibrating the Sound Level Section";
htxt[n++]=" ";
htxt[n++]="The Sound  level  meter function can be calibrated to an external ";
htxt[n++]="sound level meter or  sound  level  calibrator  by use of the ";
htxt[n++]="buttons to the left of the Sound Volume window.  Clicking changes ";
htxt[n++]="the indicated level by 1dB or by 0.1dB per click.";
htxt[n++]=" ";
htxt[n++]="Calibration will only hold  good  until any change is made to the ";
htxt[n++]="relevant Windows Volume Control  fader or until a different input ";
htxt[n++]="device is used. ";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 6 - Spectrum or Harmonic Analysis (Frequency Domain)";
htxt[n++]=" ";
htxt[n++]="6.1 Fast Fourier Transforms (FFT)";
htxt[n++]=" ";
htxt[n++]="Fast Fourier Transform is a technique  by  which incoming signals ";
htxt[n++]="can be analysed to illustrate their harmonic structure.  Harmonic ";
htxt[n++]="structure gives  us  information  about  the tone quality that an ";
htxt[n++]="instrument and player can achieve.";
htxt[n++]=" ";
htxt[n++]="The graphical  pattern  produced  by an FFT is sometimes called a ";
htxt[n++]="spectrum.  It shows the various  harmonics  as peaks rising above ";
htxt[n++]="the background noise.   The lowest harmonic is the fundamental or ";
htxt[n++]="first harmonic.  Even-numbered harmonics (2, 4, 6 etc) contribute ";
htxt[n++]="to warmth of tone.   Odd-numbered harmonics  (3, 5, 7 etc) contri-";
htxt[n++]="bute to brightness. ";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="6.2  Enabling FFT mode.";
htxt[n++]=" ";
htxt[n++]="Two sets of three FFT ranges can be selected in the Display pull-";
htxt[n++]="down.  Choose whichever gives the best results for the instrument ";
htxt[n++]="in use.  Logarithmic scales are normally used for sound to give a ";
htxt[n++]="more meaningful indication.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="6.4 Identifying the frequency and amplitude of peaks";
htxt[n++]=" ";
htxt[n++]="By pressing the left mouse button over a peak shown in the FFT ";
htxt[n++]="screen, the frequency of the peak can be found.  Because of the ";
htxt[n++]="FFT resolution, it will be accurate only within a few Hz.  At ";
htxt[n++]="the same time, the level of the peak selected will be shown at ";
htxt[n++]="the left.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="6.5 Comparing spectra of different instruments or players";
htxt[n++]=" ";
htxt[n++]="Spectra from other instruments or players can be saved and compar-";
htxt[n++]="ed with the current spectra. This very useful feature requires the ";
htxt[n++]="Sample Recording Mode and will be dealt with under that heading. ";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 7 - Wave data (Time Domain)";
htxt[n++]=" ";
htxt[n++]="7.1  Displaying Wave Forms";
htxt[n++]=" ";
htxt[n++]="The  waveform  of incoming signals can be displayed  by selecting ";
htxt[n++]="one of the three Wave Data  options  from  the Display  pull-down.  ";
htxt[n++]="Choose the option that gives the most useful image.";
htxt[n++]=" ";
htxt[n++]="7.2 Comparing wave forms";
htxt[n++]=" ";
htxt[n++]="Waveforms  from  other  instruments  or  players can be saved and ";
htxt[n++]="compared with the current wave form.   This  very  useful feature ";
htxt[n++]="requires the Sample Recording Mode  and  will be dealt with under ";
htxt[n++]="that heading. ";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 8 - Fingering patterns";
htxt[n++]=" ";
htxt[n++]="The  Auto  Tuner  contains fingering illustrations for a range of ";
htxt[n++]="Japanese and Western wind  instruments.  These  can  be  selected ";
htxt[n++]="either from the Instrument pull-down menu, or by using the Instru-";
htxt[n++]="ment select buttons at the bottom right of the panel.";
htxt[n++]=" ";
htxt[n++]="Some instruments (eg Ocarina) are available in many keys.For such ";
htxt[n++]="instruments,the Key buttons to the right of the Instrument buttons ";
htxt[n++]="permit choosing the appropriate key to the instrument.  This will ";
htxt[n++]="ensure that the fingering pattern is correct for any note.  ";
htxt[n++]=" ";
htxt[n++]="In the Manual mode, the fingering for any particular note  can be ";
htxt[n++]="found by scrolling with the note select  buttons above the instru-";
htxt[n++]="ment window.  In the Automatic mode, the fingerings  will  follow ";
htxt[n++]="the incoming sound. ";
htxt[n++]=" ";
htxt[n++]="Note names instead of instrumental fingerings can be chosen with ";
htxt[n++]="the CDE/do.re.me option. This is useful for instruments not listed.";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 9 - Sample Recording ";
htxt[n++]=" ";
htxt[n++]="9.1  Real Time and Recorded Sample Modes";
htxt[n++]=" ";
htxt[n++]="So far  we  have operated  the Auto Tuner in Real Time Mode - all ";
htxt[n++]="measurements relate to the  sound  coming  into the Tuner at that ";
htxt[n++]="instant.   But  the  Tuner  has  also been keeping a continuously ";
htxt[n++]="updated record of the last 1100 samples - these are illustrated as ";
htxt[n++]="separate  vertical lines in the Sample window on the right of the ";
htxt[n++]="panel.";
htxt[n++]=" ";
htxt[n++]="The ability to capture the last 1100 samples enables the player to ";
htxt[n++]="play  a number  of notes without putting down the instrument, and ";
htxt[n++]="then review the results.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="9.2 Controlling the Sample Recording process";
htxt[n++]=" ";
htxt[n++]="Pressing the Enter key will stop  and start the  Sample recording ";
htxt[n++]="process.  Alternatively,  use  the mouse to press  the  Run/Pause ";
htxt[n++]="button at the bottom right of the Sample window.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="9.3  Clearing the Sample memory";
htxt[n++]=" ";
htxt[n++]="Press the Clear Memory button with the mouse to clear the memory.";
htxt[n++]=" ";
htxt[n++]="Pressing  Shift-Return on the keyboard will also clear the memory ";
htxt[n++]="and recommence recording automatically.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="9.4 Scrolling through the recorded Samples";
htxt[n++]=" ";
htxt[n++]="Individual samples can be chosen by:";
htxt[n++]=" ";
htxt[n++]="- selecting from the sample window using the mouse (in FFT or ";
htxt[n++]="  Wave modes)";
htxt[n++]="- Using the Fast Forward and Rewind buttons below the sample ";
htxt[n++]="  window";
htxt[n++]="- Using the Keyboard Right and Left Arrow buttons";
htxt[n++]=" ";
htxt[n++]="Depending on which display mode you were in during sample record-";
htxt[n++]="ing, the following information is available about each sample:";
htxt[n++]=" ";
htxt[n++]="- Pitch (in semitones and cents)";
htxt[n++]="- Frequency (in Hz)";
htxt[n++]="- Sound Volume (in dB)";
htxt[n++]="- Fingering pattern";
htxt[n++]="- Wave or FFT image";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="9.5 Saving particular sample Wave or FFT data";
htxt[n++]=" ";
htxt[n++]="While a particular sample is selected,  its  Wave or FFT data may ";
htxt[n++]="be saved to disk for later comparison with current samples. Press";
htxt[n++]="the SAVE button and provide a name for the data.   Press Enter to ";
htxt[n++]="save.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="9.6 Retreiving saved sample data";
htxt[n++]=" ";
htxt[n++]="Press LOAD to retrieve a particular  sample  for comparison.  The ";
htxt[n++]="Wave or FFT image will appear in black on the screen. ";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="9.7  Hiding comparison data";
htxt[n++]=" ";
htxt[n++]="Pressing the black square button to the right of LOAD will toggle ";
htxt[n++]="the comparison data to and from the screen.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 10 - Exporting Pitch data";
htxt[n++]=" ";
htxt[n++]="10.1 Displaying accumulated pitch data";
htxt[n++]=" ";
htxt[n++]="Selecting Freq. Variation from the  Display  pull  down menu will ";
htxt[n++]="show a list of the notes and deviations in cents for the last 150 ";
htxt[n++]="or so samples.  As an example,\"C4:-09\" means 9 cents below C4 (C4 ";
htxt[n++]="is middle C).";
htxt[n++]=" ";
htxt[n++]="At the same time, a graph representing the deviation from the ";
htxt[n++]="nearest standard note (ie the cents value) will be generated.  ";
htxt[n++]="Each horizontal grid line on the graph is 10cents higher or lower ";
htxt[n++]="than the next, with the zero deviation line shown bolded.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="10.2  Accessing the sampled data";
htxt[n++]=" ";
htxt[n++]="The sampled Frequency Variation can only  be  accessed  when  the ";
htxt[n++]="Sampling process has been paused.   Press  the keyboard Enter key ";
htxt[n++]="or use the mouse to press the Pause button on the panel. Specific";
htxt[n++]="samples can then be checked by using the computer L and R arrow ";
htxt[n++]="keys, the fast forward and rewind keys on the tuner, or by selecting ";
htxt[n++]="from the Variation list with the mouse.  The relevant sample on ";
htxt[n++]="the graph is shown bolded.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="10.4  Selecting and saving desired data";
htxt[n++]=" ";
htxt[n++]="The desired data can  be  selected  by  clicking and dragging the ";
htxt[n++]="mouse over the data  screen.  Pressing  SAVE  will then request a ";
htxt[n++]="file name.  Press Enter after providing a file name.  A file with ";
htxt[n++]="a .tx8 extension will be created in the Tuner directory.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="10.3  Reloading saved data";
htxt[n++]=" ";
htxt[n++]="Pressing  LOAD  while  in Frequency Variation mode will request a ";
htxt[n++]="file name  to  load.   Other programs such as Notepad or Excel can ";
htxt[n++]="also be used to access the saved data.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
htxt[n++]=" ";
htxt[n++]="SECTION 11 - Credits and Historical Notes";
htxt[n++]=" ";
htxt[n++]="The Auto Tuner,  previously titled Shakuhachi Tuner, was designed ";
htxt[n++]="by Tatsuaki Koroda  for  the  benefit  of  Shakuhachi players and ";
htxt[n++]="makers.   At the request  of  international  makers,  players and ";
htxt[n++]="researchers of other instruments, it has been expanded to provide ";
htxt[n++]="a wider range of facilities.     Development of the Auto Tuner is ";
htxt[n++]="continuing.Comments on and suggested improvements to the software ";
htxt[n++]="should be directed to: tatsuaki@orange.ocn.ne.jp / www.shaku6.com";
htxt[n++]=" ";
htxt[n++]="These operating notes have been compiled by Australian flute maker,";
htxt[n++]="restorer and researcher, Terry McGee, http://www.mcgee-flutes.com. ";
htxt[n++]="Comments and suggested improvements regarding the notes should be ";
htxt[n++]="directed to: terry@mcgee-flutes.com.";
htxt[n++]=" ";
htxt[n++]=" ";
htxt[n++]="-------------------------------------------------------------------";
#endif
	htxt[n++]="";
	for(i=0;strlen(htxt[i])!=0;i++){
		m_help.InsertString(-1,htxt[i]);//sortしない
	}
	
	return TRUE;  // コントロールにフォーカスを設定しないとき、戻り値は TRUE となります
	              // 例外: OCX プロパティ ページの戻り値は FALSE となります
}
